apiVersion: v1
kind: Service
metadata:
  name: {{ include "finetune-platform.fullname" . }}
  labels:
    {{- include "finetune-platform.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "finetune-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: ui
      port: {{ .Values.ports.ui }}
      targetPort: ui
    - name: inference
      port: {{ .Values.ports.inference }}
      targetPort: inference
